server:
  port: 8080 # 后端API端口号

solon:
  logging:
    appender:
      console:  # 控制台输出
        level: INFO # 输出级别为INFO的日志
      file:  # 文件输出
        level: INFO  # 输出级别为INFO的日志
  dataSources:
    ds1!: # 数据源-ds1
      class: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/sadmin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456..

easy-query:
  ds1:  # 数据源-ds1
    database: mysql # 数据库类型设置为mysql
    print-sql: true # 打印SQL日志

redis:
  rd1: # 数据源-ds1
    server: localhost:6379  # Redis服务地址
    db: 1 # Redis数据库编号

sa-token:
  token-name: authtoken # Token名称
  timeout: 2592000  # Token有效期
  is-concurrent: false # 是否允许同一账号并发登录
  token-style: uuid # Token风格
  is-log: true # 打印日志
